"""fees

Revision ID: 0d5d7a3d2701
Revises: ffe90c6a066e
Create Date: 2026-10-08 06:25:13.760126

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from app.db.rls import disable_tenant_rls, enable_tenant_rls, if_app_role

NEW_TENANT_TABLES = [
    "fee_items",
    "fee_schedule",
    "invoice_counters",
    "invoice_lines",
    "invoices",
    "ledger_entries",
    "payment_intents",
    "student_discounts",
    "transfer_proofs",
]
NEW_GLOBAL_TABLES = ["paystack_events", "paystack_references"]

# revision identifiers, used by Alembic.
revision: str = "0d5d7a3d2701"
down_revision: str | Sequence[str] | None = "ffe90c6a066e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paystack_events",
        sa.Column("event_key", sa.String(length=200), nullable=False),
        sa.Column("event", sa.String(length=60), nullable=False),
        sa.Column("reference", sa.String(length=100), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paystack_events")),
        sa.UniqueConstraint("event_key", name=op.f("uq_paystack_events_event_key")),
    )
    op.create_index(
        op.f("ix_paystack_events_reference"), "paystack_events", ["reference"], unique=False
    )
    op.create_table(
        "fee_items",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_optional", sa.Boolean(), nullable=False),
        sa.Column("sort", sa.SmallInteger(), nullable=False),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_fee_items_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fee_items")),
        sa.UniqueConstraint("school_id", "id", name="uq_fee_items_school_id_id"),
        sa.UniqueConstraint("school_id", "name", name="uq_fee_items_name"),
    )
    op.create_index(op.f("ix_fee_items_school_id"), "fee_items", ["school_id"], unique=False)
    op.create_table(
        "paystack_references",
        sa.Column("reference", sa.String(length=100), nullable=False),
        sa.Column("owner_school_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_school_id"],
            ["schools.id"],
            name=op.f("fk_paystack_references_owner_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paystack_references")),
        sa.UniqueConstraint("reference", name=op.f("uq_paystack_references_reference")),
    )
    op.create_table(
        "fee_schedule",
        sa.Column("fee_item_id", sa.Uuid(), nullable=False),
        sa.Column("class_level_id", sa.Uuid(), nullable=False),
        sa.Column("term_id", sa.Uuid(), nullable=False),
        sa.Column("amount_kobo", sa.BigInteger(), nullable=False),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount_kobo >= 0", name=op.f("ck_fee_schedule_amount_non_negative")),
        sa.ForeignKeyConstraint(
            ["school_id", "class_level_id"],
            ["class_levels.school_id", "class_levels.id"],
            name="fk_class_level_id_class_levels",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "fee_item_id"],
            ["fee_items.school_id", "fee_items.id"],
            name="fk_fee_item_id_fee_items",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "term_id"],
            ["terms.school_id", "terms.id"],
            name="fk_term_id_terms",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_fee_schedule_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fee_schedule")),
        sa.UniqueConstraint(
            "school_id", "fee_item_id", "class_level_id", "term_id", name="uq_fee_schedule_cell"
        ),
        sa.UniqueConstraint("school_id", "id", name="uq_fee_schedule_school_id_id"),
    )
    op.create_index(op.f("ix_fee_schedule_school_id"), "fee_schedule", ["school_id"], unique=False)
    op.create_table(
        "invoice_counters",
        sa.Column("term_id", sa.Uuid(), nullable=False),
        sa.Column("last_seq", sa.Integer(), nullable=False),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "term_id"],
            ["terms.school_id", "terms.id"],
            name="fk_term_id_terms",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_invoice_counters_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoice_counters")),
        sa.UniqueConstraint("school_id", "id", name="uq_invoice_counters_school_id_id"),
        sa.UniqueConstraint("school_id", "term_id", name="uq_invoice_counters_term"),
    )
    op.create_index(
        op.f("ix_invoice_counters_school_id"), "invoice_counters", ["school_id"], unique=False
    )
    op.create_table(
        "student_discounts",
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("fee_item_id", sa.Uuid(), nullable=True),
        sa.Column("percent", sa.SmallInteger(), nullable=True),
        sa.Column("fixed_kobo", sa.BigInteger(), nullable=True),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(percent IS NULL) <> (fixed_kobo IS NULL)",
            name=op.f("ck_student_discounts_percent_xor_fixed"),
        ),
        sa.CheckConstraint(
            "fixed_kobo IS NULL OR fixed_kobo > 0", name=op.f("ck_student_discounts_fixed_positive")
        ),
        sa.CheckConstraint(
            "percent IS NULL OR (percent > 0 AND percent <= 100)",
            name=op.f("ck_student_discounts_percent_range"),
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "fee_item_id"],
            ["fee_items.school_id", "fee_items.id"],
            name="fk_fee_item_id_fee_items",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "student_id"],
            ["students.school_id", "students.id"],
            name="fk_student_id_students",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_student_discounts_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_discounts")),
        sa.UniqueConstraint("school_id", "id", name="uq_student_discounts_school_id_id"),
    )
    op.create_index(
        op.f("ix_student_discounts_school_id"), "student_discounts", ["school_id"], unique=False
    )
    op.create_table(
        "invoices",
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("enrollment_id", sa.Uuid(), nullable=False),
        sa.Column("term_id", sa.Uuid(), nullable=False),
        sa.Column("reference", sa.String(length=40), nullable=False),
        sa.Column("total_kobo", sa.BigInteger(), nullable=False),
        sa.Column("due_on", sa.Date(), nullable=True),
        sa.Column("results_exempt", sa.Boolean(), nullable=False),
        sa.Column("issued_by", sa.Uuid(), nullable=True),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("total_kobo >= 0", name=op.f("ck_invoices_total_non_negative")),
        sa.ForeignKeyConstraint(
            ["issued_by"],
            ["users.id"],
            name=op.f("fk_invoices_issued_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "enrollment_id"],
            ["enrollments.school_id", "enrollments.id"],
            name="fk_enrollment_id_enrollments",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "student_id"],
            ["students.school_id", "students.id"],
            name="fk_student_id_students",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "term_id"],
            ["terms.school_id", "terms.id"],
            name="fk_term_id_terms",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_invoices_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoices")),
        sa.UniqueConstraint("school_id", "id", name="uq_invoices_school_id_id"),
        sa.UniqueConstraint("school_id", "reference", name="uq_invoices_reference"),
        sa.UniqueConstraint("school_id", "student_id", "term_id", name="uq_invoices_student_term"),
    )
    op.create_index(op.f("ix_invoices_school_id"), "invoices", ["school_id"], unique=False)
    op.create_table(
        "invoice_lines",
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("fee_item_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column("amount_kobo", sa.BigInteger(), nullable=False),
        sa.Column("sort", sa.SmallInteger(), nullable=False),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "fee_item_id"],
            ["fee_items.school_id", "fee_items.id"],
            name="fk_fee_item_id_fee_items",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "invoice_id"],
            ["invoices.school_id", "invoices.id"],
            name="fk_invoice_id_invoices",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_invoice_lines_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoice_lines")),
        sa.UniqueConstraint("school_id", "id", name="uq_invoice_lines_school_id_id"),
    )
    op.create_index(
        op.f("ix_invoice_lines_school_id"), "invoice_lines", ["school_id"], unique=False
    )
    op.create_table(
        "ledger_entries",
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "payment",
                "refund",
                "adjustment",
                name="entrykind",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "paystack",
                "transfer",
                "cash",
                "manual",
                name="entrysource",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("amount_kobo", sa.BigInteger(), nullable=False),
        sa.Column("external_ref", sa.String(length=100), nullable=True),
        sa.Column("receipt_no", sa.String(length=40), nullable=True),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column("recorded_by", sa.Uuid(), nullable=True),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(kind = 'adjustment' AND amount_kobo <> 0) OR (kind <> 'adjustment' AND amount_kobo > 0)",
            name=op.f("ck_ledger_entries_amount_sign"),
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by"],
            ["users.id"],
            name=op.f("fk_ledger_entries_recorded_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "invoice_id"],
            ["invoices.school_id", "invoices.id"],
            name="fk_invoice_id_invoices",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_ledger_entries_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ledger_entries")),
        sa.UniqueConstraint("school_id", "external_ref", name="uq_ledger_entries_external_ref"),
        sa.UniqueConstraint("school_id", "id", name="uq_ledger_entries_school_id_id"),
        sa.UniqueConstraint("school_id", "receipt_no", name="uq_ledger_entries_receipt_no"),
    )
    op.create_index(
        op.f("ix_ledger_entries_school_id"), "ledger_entries", ["school_id"], unique=False
    )
    op.create_table(
        "payment_intents",
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("reference", sa.String(length=100), nullable=False),
        sa.Column("amount_kobo", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "succeeded",
                "failed",
                name="intentstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("payer_user_id", sa.Uuid(), nullable=True),
        sa.Column("gateway_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["payer_user_id"],
            ["users.id"],
            name=op.f("fk_payment_intents_payer_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "invoice_id"],
            ["invoices.school_id", "invoices.id"],
            name="fk_invoice_id_invoices",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_payment_intents_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_intents")),
        sa.UniqueConstraint("school_id", "id", name="uq_payment_intents_school_id_id"),
        sa.UniqueConstraint("school_id", "reference", name="uq_payment_intents_reference"),
    )
    op.create_index(
        op.f("ix_payment_intents_school_id"), "payment_intents", ["school_id"], unique=False
    )
    op.create_table(
        "transfer_proofs",
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("submitted_by", sa.Uuid(), nullable=True),
        sa.Column("claimed_amount_kobo", sa.BigInteger(), nullable=False),
        sa.Column("bank_reference", sa.String(length=100), nullable=True),
        sa.Column("paid_on", sa.Date(), nullable=True),
        sa.Column("file", sa.LargeBinary(), nullable=False),
        sa.Column("content_type", sa.String(length=40), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "confirmed",
                "rejected",
                name="proofstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("confirmed_amount_kobo", sa.BigInteger(), nullable=True),
        sa.Column("review_note", sa.String(length=300), nullable=True),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duplicate_of", sa.Uuid(), nullable=True),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "claimed_amount_kobo > 0", name=op.f("ck_transfer_proofs_claimed_positive")
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
            name=op.f("fk_transfer_proofs_reviewed_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "duplicate_of"],
            ["transfer_proofs.school_id", "transfer_proofs.id"],
            name="fk_duplicate_of_transfer_proofs",
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "invoice_id"],
            ["invoices.school_id", "invoices.id"],
            name="fk_invoice_id_invoices",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_transfer_proofs_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by"],
            ["users.id"],
            name=op.f("fk_transfer_proofs_submitted_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transfer_proofs")),
        sa.UniqueConstraint("school_id", "id", name="uq_transfer_proofs_school_id_id"),
    )
    op.create_index(
        op.f("ix_transfer_proofs_school_id"), "transfer_proofs", ["school_id"], unique=False
    )
    op.create_index(op.f("ix_transfer_proofs_sha256"), "transfer_proofs", ["sha256"], unique=False)
    # ### end Alembic commands ###

    for table in NEW_TENANT_TABLES:
        enable_tenant_rls(table)
    for table in NEW_TENANT_TABLES + NEW_GLOBAL_TABLES:
        if_app_role(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table} TO dl360_app")
    # Money records are append-only for the app (R21): corrections are new entries.
    if_app_role("REVOKE UPDATE, DELETE ON ledger_entries FROM dl360_app")
    if_app_role("REVOKE UPDATE, DELETE ON invoice_lines FROM dl360_app")
    if_app_role("REVOKE DELETE ON invoices FROM dl360_app")
    if_app_role("REVOKE UPDATE, DELETE ON paystack_events FROM dl360_app")
    if_app_role("GRANT UPDATE (processed_at, error) ON paystack_events TO dl360_app")


def downgrade() -> None:
    """Downgrade schema."""
    for table in NEW_TENANT_TABLES:
        disable_tenant_rls(table)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transfer_proofs_sha256"), table_name="transfer_proofs")
    op.drop_index(op.f("ix_transfer_proofs_school_id"), table_name="transfer_proofs")
    op.drop_table("transfer_proofs")
    op.drop_index(op.f("ix_payment_intents_school_id"), table_name="payment_intents")
    op.drop_table("payment_intents")
    op.drop_index(op.f("ix_ledger_entries_school_id"), table_name="ledger_entries")
    op.drop_table("ledger_entries")
    op.drop_index(op.f("ix_invoice_lines_school_id"), table_name="invoice_lines")
    op.drop_table("invoice_lines")
    op.drop_index(op.f("ix_invoices_school_id"), table_name="invoices")
    op.drop_table("invoices")
    op.drop_index(op.f("ix_student_discounts_school_id"), table_name="student_discounts")
    op.drop_table("student_discounts")
    op.drop_index(op.f("ix_invoice_counters_school_id"), table_name="invoice_counters")
    op.drop_table("invoice_counters")
    op.drop_index(op.f("ix_fee_schedule_school_id"), table_name="fee_schedule")
    op.drop_table("fee_schedule")
    op.drop_table("paystack_references")
    op.drop_index(op.f("ix_fee_items_school_id"), table_name="fee_items")
    op.drop_table("fee_items")
    op.drop_index(op.f("ix_paystack_events_reference"), table_name="paystack_events")
    op.drop_table("paystack_events")
    # ### end Alembic commands ###
