"""tenancy core

Revision ID: 99770864d2de
Revises:
Create Date: 2026-10-07 12:28:10.103134

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from app.db.rls import disable_tenant_rls, enable_tenant_rls, if_app_role

# Tables carrying school_id at this revision. Listed explicitly: migrations must not depend
# on live model metadata. tests/test_tenancy.py checks every school_id table has a policy.
TENANT_TABLES = [
    "academic_sessions",
    "arms",
    "audit_log",
    "class_levels",
    "enrollments",
    "guardians",
    "houses",
    "level_subjects",
    "memberships",
    "sections",
    "streams",
    "student_guardians",
    "students",
    "subjects",
    "terms",
]

# revision identifiers, used by Alembic.
revision: str = "99770864d2de"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schools",
        sa.Column("slug", sa.String(length=63), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("motto", sa.String(length=200), nullable=True),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column(
            "branding",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "settings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schools")),
        sa.UniqueConstraint("slug", name=op.f("uq_schools_slug")),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column(
            "must_change_password", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("totp_secret_enc", sa.String(length=255), nullable=True),
        sa.Column("totp_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "recovery_code_hashes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("phone", name="uq_users_phone"),
    )
    op.create_index(
        "uq_users_email_lower", "users", [sa.literal_column("lower(email)")], unique=True
    )
    op.create_table(
        "academic_sessions",
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_academic_sessions_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_academic_sessions")),
        sa.UniqueConstraint("school_id", "id", name="uq_academic_sessions_school_id_id"),
        sa.UniqueConstraint("school_id", "name", name="uq_academic_sessions_name"),
    )
    op.create_index(
        op.f("ix_academic_sessions_school_id"), "academic_sessions", ["school_id"], unique=False
    )
    op.create_table(
        "audit_log",
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=True),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_log_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_audit_log_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
        sa.UniqueConstraint("school_id", "id", name="uq_audit_log_school_id_id"),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_index(op.f("ix_audit_log_school_id"), "audit_log", ["school_id"], unique=False)
    op.create_table(
        "guardians",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("address_enc", sa.String(length=2000), nullable=True),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_guardians_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_guardians_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_guardians")),
        sa.UniqueConstraint("school_id", "id", name="uq_guardians_school_id_id"),
    )
    op.create_index(op.f("ix_guardians_email"), "guardians", ["email"], unique=False)
    op.create_index(op.f("ix_guardians_phone"), "guardians", ["phone"], unique=False)
    op.create_index(op.f("ix_guardians_school_id"), "guardians", ["school_id"], unique=False)
    op.create_index(op.f("ix_guardians_user_id"), "guardians", ["user_id"], unique=False)
    op.create_table(
        "houses",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_houses_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_houses")),
        sa.UniqueConstraint("school_id", "id", name="uq_houses_school_id_id"),
        sa.UniqueConstraint("school_id", "name", name="uq_houses_name"),
    )
    op.create_index(op.f("ix_houses_school_id"), "houses", ["school_id"], unique=False)
    op.create_table(
        "sections",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "creche",
                "nursery",
                "primary",
                "junior_secondary",
                "senior_secondary",
                "other",
                name="sectionkind",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "assessment_mode",
            sa.Enum(
                "scored",
                "developmental",
                "mixed",
                name="assessmentmode",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("student_login_enabled", sa.Boolean(), nullable=False),
        sa.Column("head_user_id", sa.Uuid(), nullable=True),
        sa.Column("sort", sa.SmallInteger(), nullable=False),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["head_user_id"],
            ["users.id"],
            name=op.f("fk_sections_head_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_sections_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sections")),
        sa.UniqueConstraint("school_id", "id", name="uq_sections_school_id_id"),
        sa.UniqueConstraint("school_id", "name", name="uq_sections_name"),
    )
    op.create_index(op.f("ix_sections_school_id"), "sections", ["school_id"], unique=False)
    op.create_table(
        "streams",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_streams_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_streams")),
        sa.UniqueConstraint("school_id", "id", name="uq_streams_school_id_id"),
        sa.UniqueConstraint("school_id", "name", name="uq_streams_name"),
    )
    op.create_index(op.f("ix_streams_school_id"), "streams", ["school_id"], unique=False)
    op.create_table(
        "subjects",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=True),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_subjects_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subjects")),
        sa.UniqueConstraint("school_id", "id", name="uq_subjects_school_id_id"),
        sa.UniqueConstraint("school_id", "name", name="uq_subjects_name"),
    )
    op.create_index(op.f("ix_subjects_school_id"), "subjects", ["school_id"], unique=False)
    op.create_table(
        "class_levels",
        sa.Column("section_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("sort", sa.SmallInteger(), nullable=False),
        sa.Column("next_level_id", sa.Uuid(), nullable=True),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "next_level_id"],
            ["class_levels.school_id", "class_levels.id"],
            name="fk_next_level_id_class_levels",
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "section_id"],
            ["sections.school_id", "sections.id"],
            name="fk_section_id_sections",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_class_levels_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_class_levels")),
        sa.UniqueConstraint("school_id", "id", name="uq_class_levels_school_id_id"),
        sa.UniqueConstraint("school_id", "section_id", "name", name="uq_class_levels_name"),
    )
    op.create_index(op.f("ix_class_levels_school_id"), "class_levels", ["school_id"], unique=False)
    op.create_table(
        "memberships",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "school_admin",
                "section_head",
                "bursar",
                "teacher",
                "counsellor",
                "parent",
                "student",
                name="role",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("section_id", sa.Uuid(), nullable=True),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "section_id"],
            ["sections.school_id", "sections.id"],
            name="fk_section_id_sections",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_memberships_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memberships_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
        sa.UniqueConstraint("school_id", "id", name="uq_memberships_school_id_id"),
        sa.UniqueConstraint(
            "school_id",
            "user_id",
            "role",
            "section_id",
            name="uq_memberships_user_role_section",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(op.f("ix_memberships_school_id"), "memberships", ["school_id"], unique=False)
    op.create_index(op.f("ix_memberships_user_id"), "memberships", ["user_id"], unique=False)
    op.create_table(
        "students",
        sa.Column("admission_no", sa.String(length=30), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("middle_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column(
            "gender",
            sa.Enum(
                "male",
                "female",
                name="gender",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("photo_key", sa.String(length=255), nullable=True),
        sa.Column("house_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "graduated",
                "withdrawn",
                name="studentstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "house_id"], ["houses.school_id", "houses.id"], name="fk_house_id_houses"
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_students_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_students_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_students")),
        sa.UniqueConstraint("school_id", "admission_no", name="uq_students_admission_no"),
        sa.UniqueConstraint("school_id", "id", name="uq_students_school_id_id"),
    )
    op.create_index(op.f("ix_students_school_id"), "students", ["school_id"], unique=False)
    op.create_index(op.f("ix_students_user_id"), "students", ["user_id"], unique=False)
    op.create_table(
        "terms",
        sa.Column("academic_session_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.SmallInteger(), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=True),
        sa.Column("ends_on", sa.Date(), nullable=True),
        sa.Column("next_term_begins", sa.Date(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "academic_session_id"],
            ["academic_sessions.school_id", "academic_sessions.id"],
            name="fk_academic_session_id_academic_sessions",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_terms_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_terms")),
        sa.UniqueConstraint("school_id", "academic_session_id", "number", name="uq_terms_number"),
        sa.UniqueConstraint("school_id", "id", name="uq_terms_school_id_id"),
    )
    op.create_index(op.f("ix_terms_school_id"), "terms", ["school_id"], unique=False)
    op.create_index(
        "uq_terms_one_current",
        "terms",
        ["school_id"],
        unique=True,
        postgresql_where=sa.text("is_current"),
    )
    op.create_table(
        "arms",
        sa.Column("class_level_id", sa.Uuid(), nullable=False),
        sa.Column("academic_session_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "academic_session_id"],
            ["academic_sessions.school_id", "academic_sessions.id"],
            name="fk_academic_session_id_academic_sessions",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "class_level_id"],
            ["class_levels.school_id", "class_levels.id"],
            name="fk_class_level_id_class_levels",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_arms_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_arms")),
        sa.UniqueConstraint(
            "school_id", "class_level_id", "academic_session_id", "name", name="uq_arms_name"
        ),
        sa.UniqueConstraint("school_id", "id", name="uq_arms_school_id_id"),
    )
    op.create_index(op.f("ix_arms_school_id"), "arms", ["school_id"], unique=False)
    op.create_table(
        "level_subjects",
        sa.Column("class_level_id", sa.Uuid(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("is_compulsory", sa.Boolean(), nullable=False),
        sa.Column("sort", sa.SmallInteger(), nullable=False),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "class_level_id"],
            ["class_levels.school_id", "class_levels.id"],
            name="fk_class_level_id_class_levels",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "subject_id"],
            ["subjects.school_id", "subjects.id"],
            name="fk_subject_id_subjects",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_level_subjects_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_level_subjects")),
        sa.UniqueConstraint(
            "school_id", "class_level_id", "subject_id", name="uq_level_subjects_pair"
        ),
        sa.UniqueConstraint("school_id", "id", name="uq_level_subjects_school_id_id"),
    )
    op.create_index(
        op.f("ix_level_subjects_school_id"), "level_subjects", ["school_id"], unique=False
    )
    op.create_table(
        "student_guardians",
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("guardian_id", sa.Uuid(), nullable=False),
        sa.Column("relationship", sa.String(length=30), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "guardian_id"],
            ["guardians.school_id", "guardians.id"],
            name="fk_guardian_id_guardians",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "student_id"],
            ["students.school_id", "students.id"],
            name="fk_student_id_students",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_student_guardians_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_guardians")),
        sa.UniqueConstraint("school_id", "id", name="uq_student_guardians_school_id_id"),
        sa.UniqueConstraint("school_id", "student_id", "guardian_id", name="uq_student_guardians"),
    )
    op.create_index(
        op.f("ix_student_guardians_school_id"), "student_guardians", ["school_id"], unique=False
    )
    op.create_table(
        "enrollments",
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("arm_id", sa.Uuid(), nullable=False),
        sa.Column("academic_session_id", sa.Uuid(), nullable=False),
        sa.Column("stream_id", sa.Uuid(), nullable=True),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "academic_session_id"],
            ["academic_sessions.school_id", "academic_sessions.id"],
            name="fk_academic_session_id_academic_sessions",
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "arm_id"], ["arms.school_id", "arms.id"], name="fk_arm_id_arms"
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "stream_id"],
            ["streams.school_id", "streams.id"],
            name="fk_stream_id_streams",
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "student_id"],
            ["students.school_id", "students.id"],
            name="fk_student_id_students",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_enrollments_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_enrollments")),
        sa.UniqueConstraint("school_id", "id", name="uq_enrollments_school_id_id"),
        sa.UniqueConstraint(
            "school_id", "student_id", "academic_session_id", name="uq_enrollments_per_session"
        ),
    )
    op.create_index(op.f("ix_enrollments_school_id"), "enrollments", ["school_id"], unique=False)
    # ### end Alembic commands ###

    for table in TENANT_TABLES:
        enable_tenant_rls(table)
    if_app_role("GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO dl360_app")
    # Audit log is append-only for the app (R25).
    if_app_role("REVOKE UPDATE, DELETE ON audit_log FROM dl360_app")


def downgrade() -> None:
    """Downgrade schema."""
    for table in TENANT_TABLES:
        disable_tenant_rls(table)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_enrollments_school_id"), table_name="enrollments")
    op.drop_table("enrollments")
    op.drop_index(op.f("ix_student_guardians_school_id"), table_name="student_guardians")
    op.drop_table("student_guardians")
    op.drop_index(op.f("ix_level_subjects_school_id"), table_name="level_subjects")
    op.drop_table("level_subjects")
    op.drop_index(op.f("ix_arms_school_id"), table_name="arms")
    op.drop_table("arms")
    op.drop_index(
        "uq_terms_one_current", table_name="terms", postgresql_where=sa.text("is_current")
    )
    op.drop_index(op.f("ix_terms_school_id"), table_name="terms")
    op.drop_table("terms")
    op.drop_index(op.f("ix_students_user_id"), table_name="students")
    op.drop_index(op.f("ix_students_school_id"), table_name="students")
    op.drop_table("students")
    op.drop_index(op.f("ix_memberships_user_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_school_id"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_index(op.f("ix_class_levels_school_id"), table_name="class_levels")
    op.drop_table("class_levels")
    op.drop_index(op.f("ix_subjects_school_id"), table_name="subjects")
    op.drop_table("subjects")
    op.drop_index(op.f("ix_streams_school_id"), table_name="streams")
    op.drop_table("streams")
    op.drop_index(op.f("ix_sections_school_id"), table_name="sections")
    op.drop_table("sections")
    op.drop_index(op.f("ix_houses_school_id"), table_name="houses")
    op.drop_table("houses")
    op.drop_index(op.f("ix_guardians_user_id"), table_name="guardians")
    op.drop_index(op.f("ix_guardians_school_id"), table_name="guardians")
    op.drop_index(op.f("ix_guardians_phone"), table_name="guardians")
    op.drop_index(op.f("ix_guardians_email"), table_name="guardians")
    op.drop_table("guardians")
    op.drop_index(op.f("ix_audit_log_school_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_academic_sessions_school_id"), table_name="academic_sessions")
    op.drop_table("academic_sessions")
    op.drop_index("uq_users_email_lower", table_name="users")
    op.drop_table("users")
    op.drop_table("schools")
    # ### end Alembic commands ###
